name: arduino-lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          # path: ./
          version: 1.x
          compliance: strict
          library-manager: update
          project-type: library
          recursive: true
          # report-file:
          verbose: false